EnvironmentConfigurationMetadata:
  Description: Configuration created from the EB CLI using "eb config save".
  DateCreated: '1684048619000'
  DateModified: '1684048619000'
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-east-1::platform/Docker running on 64bit
    Amazon Linux 2/3.5.7
OptionSettings:
  aws:ec2:instances:
    SpotFleetOnDemandAboveBasePercentage: '0'
    InstanceTypes: t3.small,t3.medium
  AWSEBEC2LaunchTemplate.aws:autoscaling:launchconfiguration:
    RootVolumeSize: '10'
    RootVolumeType: gp3
  aws:elasticbeanstalk:environment:
    ServiceRole: arn:aws:iam::620684953042:role/aws-elasticbeanstalk-service-role
    EnvironmentType: SingleInstance
  aws:elasticbeanstalk:healthreporting:system:
    ConfigDocument:
      Version: 1
      CloudWatchMetrics:
        Instance:
          RootFilesystemUtil: 60
          CPUIrq: 60
          LoadAverage5min: 60
          ApplicationRequests5xx: 60
          ApplicationRequests4xx: 60
          CPUUser: 60
          LoadAverage1min: 60
          ApplicationLatencyP50: 60
          CPUIdle: 60
          InstanceHealth: 60
          ApplicationLatencyP95: 60
          ApplicationLatencyP85: 60
          ApplicationLatencyP90: 60
          CPUSystem: 60
          ApplicationLatencyP75: 60
          CPUSoftirq: 60
          ApplicationLatencyP10: 60
          ApplicationLatencyP99: 60
          ApplicationRequestsTotal: 60
          ApplicationRequests3xx: 60
          ApplicationLatencyP99.9: 60
          ApplicationRequests2xx: 60
          CPUIowait: 60
          CPUNice: 60
        Environment: {}
      Rules:
        Environment:
          ELB:
            ELBRequests4xx:
              Enabled: true
          Application:
            ApplicationRequests4xx:
              Enabled: true
  aws:autoscaling:launchconfiguration:
    SecurityGroups: bondy-vpc-security-group
    DisableIMDSv1: true
    EC2KeyName: bondy-eb-ec2
  AWSEBAutoScalingLaunchConfiguration.aws:autoscaling:launchconfiguration:
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
  aws:elasticbeanstalk:managedactions:
    ManagedActionsEnabled: true
    PreferredStartTime: MON:11:11
  aws:elasticbeanstalk:managedactions:platformupdate:
    UpdateLevel: minor
  aws:elasticbeanstalk:cloudwatch:logs:health:
    RetentionInDays: '30'
    HealthStreamingEnabled: true
EnvironmentTier:
  Type: Standard
  Name: WebServer
AWSConfigurationTemplateVersion: 1.1.0.0
